(progn
  (require 'org)
  (require 'ob-python)
  (require 'ob-R)
  (require 'ob-js)
  (require 'ob-julia)
  (require 'ob-octave)
  (require 'ob-ruby)
  (require 'ob-perl)
  (require 'ob-lua)
  (require 'ob-fortran)
  (require 'ob-java)
  (require 'ob-maxima)
  (setq org-confirm-babel-evaluate nil)
)
