
;; NOTE: ESS needs to be before org-mode

;; packages/init.el
(unless (package-installed-p 'vc-use-package)
  (package-vc-install "https://github.com/slotThe/vc-use-package"))
(require 'vc-use-package)

(setq package-dir (concat config-dir "./packages/"))

(message "Loading packages from %s" package-dir)
(load (concat package-dir "mep-all-the-icons.el") t)
(load (concat package-dir "mep-affe.el") t)
(load (concat package-dir "mep-bash-completion.el") t)
(load (concat package-dir "mep-consult.el") t)
(load (concat package-dir "mep-corfu.el") t)
(load (concat package-dir "mep-dashboard.el") t)
(load (concat package-dir "mep-doom-modeline.el") t)
(load (concat package-dir "mep-evil-collection.el") t)
(load (concat package-dir "mep-evil.el") t)
(load (concat package-dir "mep-flycheck.el") t)
(load (concat package-dir "mep-gptel.el") t)
(load (concat package-dir "mep-grip-mode.el") t)
(load (concat package-dir "mep-htmlize.el") t)
(load (concat package-dir "mep-lsp-bridge.el") t)
(load (concat package-dir "mep-lsp-mode.el") t)
(load (concat package-dir "mep-lsp-ui.el") t)
(load (concat package-dir "mep-lsp-java.el") t)
(load (concat package-dir "mep-marginalia.el") t)
(load (concat package-dir "mep-markdown-mode.el") t)
(load (concat package-dir "mep-neotree.el") t)
(load (concat package-dir "mep-orderless.el") t)
(load (concat package-dir "mep-org-mode.el") t)
(load (concat package-dir "mep-org-gtd.el") t)
(load (concat package-dir "mep-org-preview-html.el") t)
(load (concat package-dir "mep-projectile.el") t)
(load (concat package-dir "mep-treemacs.el") t)
(load (concat package-dir "mep-vertico.el") t)
(load (concat package-dir "mep-which-key.el") t)
(load (concat package-dir "mep-yasnippet.el") t)
(load (concat package-dir "mep-zenmode.el") t)
(load (concat package-dir "mep-ivy.el") t)
(load (concat package-dir "mep-perspective.el") t)
(load (concat package-dir "mep-general.el") t)
(load (concat package-dir "mep-dap-mode.el") t)
(load (concat package-dir "mep-cmake-mode.el") t)
(load (concat package-dir "mep-ox-gfm.el") t)
(load (concat package-dir "mep-anaconda-mode.el") t)
(load (concat package-dir "mep-texfrag.el") t)
(load (concat package-dir "mep-auxtex.el") t)
(load (concat package-dir "mep-vimish-fold.el") t)
(load (concat package-dir "mep-org-modern.el") t)
(load (concat package-dir "mep-golden-ratio.el") t)
(load (concat package-dir "mep-emacs-direnv.el") t)
(load (concat package-dir "mep-doom-themes.el") t)
(load (concat package-dir "mep-vterm.el") t)
(load (concat package-dir "mep-ess.el") t)
(load (concat package-dir "mep-haskell-mode.el") t)
(load (concat package-dir "mep-ob-async.el") t)
(load (concat package-dir "mep-ob-nix.el") t)
(load (concat package-dir "mep-ob-mermaid.el") t)
(load (concat package-dir "mep-ob-crystal.el") t)
(load (concat package-dir "mep-ob-elm.el") t)
(load (concat package-dir "mep-ob-gleam.el") t)
(load (concat package-dir "mep-ob-go.el") t)
(load (concat package-dir "mep-ob-nim.el") t)
(load (concat package-dir "mep-ob-prolog.el") t)
(load (concat package-dir "mep-ob-rust.el") t)
(load (concat package-dir "mep-tuareg.el") t)
(load (concat package-dir "mep-slime.el") t)
(load (concat package-dir "mep-emacs-gnuplot.el") t)

;; (load (concat package-dir "mep-magit.el") t)
;; (load (concat package-dir "mep-org-roam.el") t)
;; (load (concat package-dir "mep-org-reveal.el") t)
;; (load "~/.emacs.d/packages/mep-git-gutter.el")

;; (load "~/.emacs.d/packages/mep-eaf.el")
;; (load "~/.emacs.d/packages/mep-company.el")
;; (load "~/.emacs.d/packages/mep-editorconfig.el")
;; (load "~/.emacs.d/packages/mep-hl-todo.el")
;; (load "~/.emacs.d/packages/mep-counsel.el")
;; (load "~/.emacs.d/packages/mep-apropospriate-theme.el")
